fix: allow dynamic item count
sparksuite/react-accessible-dropdown-menu-hook pull request #78
Opened 2020-01-27 12:50 UTC by tanguyantoine

# What

Add a `useEffect` hook that populate items refs.

# Why

It allows dynamic item count

use case

```tsx
const MyCompontent = () => {
  const [items, setItems] = useState(['1', '2'])
  const { buttonProps, itemProps, isOpen, setIsOpen } = useDropdownMenu(items.length)
  setTimeout(() => {
    setItems([...items, '3'])
  }, 3000)

  return (
    <ul>
      {items.map((item, index) => (
        <li key={item} {...itemProps[index]}>
          <a>{item}</a>
        </li>
      ))}
    </ul>
  )
}
```

2020-01-27 13:08 UTC, tanguyantoine commented
interesting, not adding code increases the coverage 🤣

2020-01-27 14:08 UTC, WesCossick requested changes
Thanks @tanguyantoine for submitting this! I made a couple of minor suggestions. Most importantly, though, can you add a unit test that would fail with our existing code, but is fixed by your changes?

This will help us avoid reintroducing this bug in the future if we ever refactor the code.

2020-01-27 14:08 UTC, WesCossick commented on src/use-dropdown-menu.ts
> +
```suggestion
```

2020-01-27 14:08 UTC, WesCossick commented on src/use-dropdown-menu.ts
> +	// Initialize refs an update them on prop changes
```suggestion
	// Initialize refs and update them when the item count changes
```

2020-01-29 00:04 UTC, corymharper commented
Good contribution @tanguyantoine!

I do have a concern about the current approach though.

Consider the following scenario:

```js
    const [items, setItems] = useState(['1', '2'..., '10,000'])
    const { buttonProps, itemProps, isOpen, setIsOpen } = useDropdownMenu(items.length)
```

In the above scenario, the hook would originally create an array of 10,000 refs, and that array would never change. The same thing happens on the first render in your current approach, but if they then add one item to the array, it scraps the old array, and creates 10,001 new refs to fill the array. 

This is an extreme example, but I think it showcases my concern, is instantiating a whole new array of refs the most optimal method for increasing or decreasing the number of refs in the array? The additional steps needed to implement a different solution may undercut any performance gains we would get from a different implementation, but I think it's worth having a discussion about.

2020-01-29 08:47 UTC, tanguyantoine commented
Would you prefer `Array.from(Array(itemCount))` ?

2020-01-29 08:50 UTC, tanguyantoine commented
Let's be realistic, why would you put 10 000 items in a dropdown? 
Let's assume you dot it, we would regenerate an array of ref if the itemCount value changes. At the moment it does not work, it is expected not to be able to change the number of items?

2020-01-29 15:41 UTC, corymharper commented
I agree with you that it's not a realistic use case, so we probably don't need to consider it. If you could review the couple of changes that @WesCossick requested, on line 23 and 36, and add a test for the change you made, simply one that verifies the ref array length is changing when items are removed or added as expected should suffice, I think this PR looks good to be merged in!

2020-01-29 17:13 UTC, tanguyantoine commented
I'll do it as soon as I get bandwidth for it

2020-03-25 22:08 UTC, closed without merging