Dynamic item count revisited
sparksuite/react-accessible-dropdown-menu-hook pull request #98
Opened 2020-03-10 19:41 UTC by corymharper

Currently the hook can only handle a list that does not change size, this PR fixes that.

closes #97

2020-03-11 15:57 UTC, WesCossick requested changes
The `yarn.lock` files shouldn't need to be updated in this PR. Also; it looks like you've organized the tests by grouping them into `describe()` blocks. Can you do this in a separate PR? It makes it hard to see what is actually being changed to fix the dynamic item bug.

2020-03-25 17:53 UTC, corymharper commented
I'm not certain why it thinks I have changed the lock file, I copied it straight from master to this branch…

2020-03-25 18:11 UTC, WesCossick requested changes
The `yarn.lock` file still has changes; it should not have any.

2020-03-25 18:33 UTC, corymharper commented
> The `yarn.lock` file still has changes; it should not have any.

My `yarn.lock` is identical to the `master` branch `yarn.lock`, I'm not certain why it thinks there are changes. The versions it is listing in the diff are not the versions on master branch currently.

2020-03-25 18:46 UTC, WesCossick commented
You may need to merge `master` into your branch.

2020-03-25 21:26 UTC, corymharper commented
> You may need to merge `master` into your branch.

I ended up rebasing off the most current HEAD of master

2020-03-25 21:30 UTC, WesCossick requested changes

2020-03-25 21:30 UTC, WesCossick commented on test/use-dropdown-menu.test.tsx
> +it('can navigate to a new item', () => {
```suggestion
it('can navigate to a dynamically-added item', () => {
```

2020-03-25 22:08 UTC, merged